export const login = '/login'
export const resetPassword = '/reset-password'
export const dashboard = '/dashboard'
export const pengaduan = '/pengaduan'
export const umkm = '/umkm'
export const statistik = '/statistik'
export const artikel = '/artikel'